export const FIRECRACKER_SECCOMP_PROFILE = {
  default_action: 'Trap',
  filter_action: 'Allow',
  filter: [
    { syscall: 'rt_sigreturn', comment: 'Allow signal handling' },
    { syscall: 'rt_sigprocmask', comment: 'Allow signal handling' },
    { syscall: 'futex', comment: 'Allow futex for threading' },
    { syscall: 'epoll_wait', comment: 'Allow epoll' },
    { syscall: 'epoll_ctl', comment: 'Allow epoll' },
    { syscall: 'epoll_create1', comment: 'Allow epoll' },
    { syscall: 'write', comment: 'Allow write to FDs' },
    { syscall: 'read', comment: 'Allow read from FDs' },
    { syscall: 'mmap', comment: 'Allow mmap' },
    { syscall: 'munmap', comment: 'Allow munmap' },
    { syscall: 'mprotect', comment: 'Allow mprotect' },
    { syscall: 'brk', comment: 'Allow brk' },
    { syscall: 'ioctl', comment: 'Allow ioctl for KVM/TAP' },
    { syscall: 'openat', comment: 'Allow opening files' },
    { syscall: 'close', comment: 'Allow closing files' },
    { syscall: 'lseek', comment: 'Allow lseek' },
    { syscall: 'fstat', comment: 'Allow fstat' },
    { syscall: 'newfstatat', comment: 'Allow newfstatat' },
    { syscall: 'readlink', comment: 'Allow readlink' },
    { syscall: 'fcntl', comment: 'Allow fcntl' },
    { syscall: 'accept4', comment: 'Allow accept4' },
    { syscall: 'bind', comment: 'Allow bind' },
    { syscall: 'connect', comment: 'Allow connect' },
    { syscall: 'listen', comment: 'Allow listen' },
    { syscall: 'socket', comment: 'Allow socket creation' },
    { syscall: 'getsockname', comment: 'Allow getsockname' },
    { syscall: 'getpeername', comment: 'Allow getpeername' },
    { syscall: 'setsockopt', comment: 'Allow setsockopt' },
    { syscall: 'getsockopt', comment: 'Allow getsockopt' },
    { syscall: 'shutdown', comment: 'Allow shutdown' },
    { syscall: 'recvfrom', comment: 'Allow recvfrom' },
    { syscall: 'sendto', comment: 'Allow sendto' },
    { syscall: 'clone', comment: 'Allow clone' },
    {
      syscall: 'execve',
      comment: 'Allow execve (for jailer mostly, but firecracker might need it for re-exec)',
    },
    { syscall: 'exit', comment: 'Allow exit' },
    { syscall: 'exit_group', comment: 'Allow exit_group' },
    { syscall: 'getuid', comment: 'Allow getuid' },
    { syscall: 'getgid', comment: 'Allow getgid' },
    { syscall: 'getpid', comment: 'Allow getpid' },
    { syscall: 'gettid', comment: 'Allow gettid' },
    { syscall: 'prctl', comment: 'Allow prctl' },
    { syscall: 'sysinfo', comment: 'Allow sysinfo' },
    { syscall: 'clock_gettime', comment: 'Allow clock_gettime' },
    { syscall: 'getrandom', comment: 'Allow getrandom' },
  ],
};

export const ALLOWED_CAPABILITIES = [
  // Empty list to drop all capabilities by default,
  // dependent on what Firecracker needs (usually runs unprivileged after setup)
];
